/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Szinhaz;

/**
 *
 * @author DobszayDorkaMária(SZ
 */
public class jegyvasarlas extends javax.swing.JFrame {

    int extra1 = 0;
    int extra2 = 0;
    int extra3 = 0;
    int extra4= 0;
    
    public jegyvasarlas() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblNev = new javax.swing.JLabel();
        lblHelyszin = new javax.swing.JLabel();
        lbljegy = new javax.swing.JLabel();
        lblPalUtca = new javax.swing.JLabel();
        lblDzsugel = new javax.swing.JLabel();
        lblPadlas = new javax.swing.JLabel();
        chbToldi = new javax.swing.JCheckBox();
        chbPal = new javax.swing.JCheckBox();
        chbPadlas = new javax.swing.JCheckBox();
        chbDzsugel = new javax.swing.JCheckBox();
        lblSzinhaz = new javax.swing.JLabel();
        btnMegvesz = new javax.swing.JButton();
        lblDb = new javax.swing.JLabel();
        sprDb = new javax.swing.JSpinner();
        pnlMusorLista = new javax.swing.JPanel();
        lblToldiKep = new javax.swing.JLabel();
        lblPalKep = new javax.swing.JLabel();
        lblPadlasKep = new javax.swing.JLabel();
        lblDzsugelKep = new javax.swing.JLabel();
        lblToldi = new javax.swing.JLabel();
        lblHely = new javax.swing.JLabel();
        pnlOsszeg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 0));

        lblNev.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        lblNev.setText("Vígszínház");

        lblHelyszin.setText("Helyszín:");

        lbljegy.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        lbljegy.setText("Jegy vétel");

        lblPalUtca.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        lblPalUtca.setText("A pál utcai fiúk");

        lblDzsugel.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        lblDzsugel.setText("A dzsugel könyve");

        lblPadlas.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        lblPadlas.setText("A padlás");

        buttonGroup1.add(chbToldi);
        chbToldi.setText("Jegyvásárlás");
        chbToldi.setActionCommand("sáslás");
        chbToldi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbToldiActionPerformed(evt);
            }
        });

        buttonGroup1.add(chbPal);
        chbPal.setText("Jegyvásárlás");
        chbPal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPalActionPerformed(evt);
            }
        });

        buttonGroup1.add(chbPadlas);
        chbPadlas.setText("Jegyvásárlás");
        chbPadlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPadlasActionPerformed(evt);
            }
        });

        buttonGroup1.add(chbDzsugel);
        chbDzsugel.setText("Jegyvásárlás");
        chbDzsugel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbDzsugelActionPerformed(evt);
            }
        });

        lblSzinhaz.setIcon(new javax.swing.ImageIcon("C:\\Users\\DobszayDorkaMária(SZ\\Pictures\\letöltés.jpg")); // NOI18N

        btnMegvesz.setText("Megveszem");

        lblDb.setText("db:");

        sprDb.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));

        pnlMusorLista.setBorder(javax.swing.BorderFactory.createTitledBorder("Műsorkép"));

        lblToldiKep.setIcon(new javax.swing.ImageIcon("C:\\Users\\DobszayDorkaMária(SZ\\Documents\\letöltés (toldi).jpg")); // NOI18N

        lblPalKep.setIcon(new javax.swing.ImageIcon("C:\\Users\\DobszayDorkaMária(SZ\\Documents\\letöltés (pál).jpg")); // NOI18N

        lblPadlasKep.setIcon(new javax.swing.ImageIcon("C:\\Users\\DobszayDorkaMária(SZ\\Documents\\letöltés (padlas).jpg")); // NOI18N

        lblDzsugelKep.setIcon(new javax.swing.ImageIcon("C:\\Users\\DobszayDorkaMária(SZ\\Documents\\letöltés (dzsugel).jpg")); // NOI18N

        javax.swing.GroupLayout pnlMusorListaLayout = new javax.swing.GroupLayout(pnlMusorLista);
        pnlMusorLista.setLayout(pnlMusorListaLayout);
        pnlMusorListaLayout.setHorizontalGroup(
            pnlMusorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMusorListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMusorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblToldiKep, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPalKep)
                    .addComponent(lblPadlasKep, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDzsugelKep, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMusorListaLayout.setVerticalGroup(
            pnlMusorListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMusorListaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblToldiKep)
                .addGap(18, 18, 18)
                .addComponent(lblPalKep)
                .addGap(18, 18, 18)
                .addComponent(lblPadlasKep)
                .addGap(18, 18, 18)
                .addComponent(lblDzsugelKep)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lblToldi.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        lblToldi.setText("Toldi");

        lblHely.setText("1137 Szent István krt. 14.");

        pnlOsszeg.setBorder(javax.swing.BorderFactory.createTitledBorder("Összeg"));

        jLabel1.setText("0");

        jLabel2.setText("Ft");

        javax.swing.GroupLayout pnlOsszegLayout = new javax.swing.GroupLayout(pnlOsszeg);
        pnlOsszeg.setLayout(pnlOsszegLayout);
        pnlOsszegLayout.setHorizontalGroup(
            pnlOsszegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOsszegLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );
        pnlOsszegLayout.setVerticalGroup(
            pnlOsszegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOsszegLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlOsszegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlMusorLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDzsugel)
                                    .addComponent(lblPadlas)
                                    .addComponent(lblPalUtca)
                                    .addComponent(lblToldi)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSzinhaz, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblNev))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(lbljegy))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(lblDb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sprDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lblHelyszin))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHely)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(chbToldi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chbPal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chbPadlas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chbDzsugel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pnlOsszeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMegvesz)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSzinhaz, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNev)
                            .addComponent(lblHelyszin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbljegy)
                            .addComponent(lblHely))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlMusorLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnMegvesz)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(lblToldi)
                                .addGap(111, 111, 111))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chbToldi)
                                .addGap(103, 103, 103)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbPal)
                            .addComponent(lblPalUtca))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPadlas)
                            .addComponent(chbPadlas))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDzsugel)
                            .addComponent(chbDzsugel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDb)
                                    .addComponent(sprDb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(pnlOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE))))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chbToldiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbToldiActionPerformed
        if (chbToldi.isSelected()) {
            extra1 = 5000;
        }
        else if (chbToldi.isSelected()== false) {
            extra1 = 0;
        }
    }//GEN-LAST:event_chbToldiActionPerformed

    private void chbPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPalActionPerformed
        if (chbPal.isSelected()) {
              extra2 = 6000;

        }
        else if (chbPal.isSelected()== false) {
            extra2 = 0;
        }
    }//GEN-LAST:event_chbPalActionPerformed

    private void chbPadlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPadlasActionPerformed
        if (chbPadlas.isSelected()) {
            extra3 = 5050;
        }
        else if (chbPadlas.isSelected()== false) {
            extra3 = 0;
        }
    }//GEN-LAST:event_chbPadlasActionPerformed

    private void chbDzsugelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbDzsugelActionPerformed
        if (chbDzsugel.isSelected()) {
            extra4 = 4000;


        }
        else if (chbDzsugel.isSelected()== false) {
            extra4 = 0;
        }
    }//GEN-LAST:event_chbDzsugelActionPerformed
        void kiszamitasAr(){
            
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jegyvasarlas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jegyvasarlas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jegyvasarlas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jegyvasarlas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jegyvasarlas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegvesz;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chbDzsugel;
    private javax.swing.JCheckBox chbPadlas;
    private javax.swing.JCheckBox chbPal;
    private javax.swing.JCheckBox chbToldi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDb;
    private javax.swing.JLabel lblDzsugel;
    private javax.swing.JLabel lblDzsugelKep;
    private javax.swing.JLabel lblHely;
    private javax.swing.JLabel lblHelyszin;
    private javax.swing.JLabel lblNev;
    private javax.swing.JLabel lblPadlas;
    private javax.swing.JLabel lblPadlasKep;
    private javax.swing.JLabel lblPalKep;
    private javax.swing.JLabel lblPalUtca;
    private javax.swing.JLabel lblSzinhaz;
    private javax.swing.JLabel lblToldi;
    private javax.swing.JLabel lblToldiKep;
    private javax.swing.JLabel lbljegy;
    private javax.swing.JPanel pnlMusorLista;
    private javax.swing.JPanel pnlOsszeg;
    private javax.swing.JSpinner sprDb;
    // End of variables declaration//GEN-END:variables
}
